package com.nc.model.message;

public enum MessageType {
    LOGIN,
    LOGOFF,
    REGISTER,
    MSG,
    ONLINE,
    OFFLINE,
    JOINCHAT,
    JOINGROUPCHAT,
    LEAVECHAT,
    LEAVEGROUPCHAT,
    UPDATEPROFILE,
    INVITEUSERTOCHAT,
    INVITEUSERSTOGROUPCHAT,
    REMOVEUSERFROMGROUPCHAT,
    REQUESTCONTACTS,
    REQUESTGROUPCHATS,
    REQUESTGROUPCHATCONTACTS,
    REQUESTBANLIST,
    ADDTOBANLIST,
    REMOVEFROMBANLIST
}
