package com.nc.model.message;

public enum MessageType {
    LOGIN,
    LOGOFF,
    REGISTER,
    MSG,
    JOINGROUPCHAT,
    LEAVEGROUPCHAT,
    UPDATEPROFILE,
    INVITEUSERTOCHAT,
    INVITEUSERSTOGROUPCHAT,
    REMOVEUSERFROMGROUPCHAT,
    ADDTOBANLIST,
    REMOVEFROMBANLIST
}
